name: i69n
description: Simple internationalization tool for Dart and Flutter, based on YAML files and source code generation.
version: 3.2.0
homepage: https://github.com/fnx-io/i69n

environment:
  sdk: ^3.6.0

dependencies:
  build: ^2.4.2
  build_config: ^1.1.2
  yaml: ^3.1.3
  dart_style: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
  build_runner: ^2.4.15
#  build_web_compilers: ^4.1.1
