name: i69n
description: Simple internationalization tool for Dart and Flutter, based on YAML files and source generation.
version: 0.4.0
homepage: https://github.com/fnx-io/i69n
author: Tomas Zverina <t@fnx.io>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  build: ^1.2.0
  build_config: ^0.4.1
  yaml: ^2.2.0
  dart_style: ">=1.2.0 <2.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.0.0
  build_runner: ^1.7.1
  build_web_compilers: ^2.5.2